### ISSUE TITLE
Auth code

### ISSUE THREAD

**Issue by mjaberster** [saguiitay/OneDriveRestAPI#2]
Anymethod available for automaticly taking the authentication code from the redirect url and substitute it in the 
// TODO: Navigate to authRequestUrl using the browser, and retrieve the Authorization Code from the response
var authCode = "...";

I tried the to do as follow:

HttpClient theClient = new HttpClient();
HttpResponseMessage response = await theClient.GetAsync(authRequestUrl);
response.EnsureSuccessStatusCode();
string responseUri = response.RequestMessage.RequestUri.ToString();
Console.Out.WriteLine(responseUri);
var authCode = ; // here i made a substring from the response uri to take the code

DIDNT WORK

Thanks

**Comment by timerickson** [comment]
You probably need to use the Location in the Response Headers collection.  Many (Most?) OAuth providers utilize redirects to the final/success location, which will contain the token, and thus will be different from the RequestUri.

**Comment by saguiitay** [comment]
Take a look at my answer here (<http://stackoverflow.com/questions/28833004/how-to-get-dropbox-files-by-dropboxrest-api-in-c/29478784#29478784>). It's regarding my DropboxRestAPI, but is very similar.

**Comment by timerickson** [comment]
Yeah - didn't see what he was asking initially, though @mjaberster 's code still appears wrong for the reason I outline.  I actually resolved the actual //TODO problem referenced for myself after forgetting about this issue and am just now working on a PR for it.

**Comment by timerickson** [comment]
@mjaberster would you like to review and close this?
