### ISSUE TITLE
ConfigureAwait(false) missing on awaitable calls

### ISSUE THREAD

**Issue by MisterD81** [saguiitay/OneDriveRestAPI#3]
ConfigureAwait(false) is missing on awaitable calls. This can lead to deadlocks when using those methods.
Therefore it would be good if this could be added like in DropboxRestApi

**Comment by saguiitay** [comment]
Resolved with 75aec5cf078748b38b14855b88f5629b6ebb671d
Updated NuGet package will be released shortly
